# Generated by Django 3.0.6 on 2020-05-12 18:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=130, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('Product_id', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('Subject', models.CharField(blank=True, max_length=200, null=True)),
                ('text_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_Entry_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(validators=[django.core.validators.MinLengthValidator(6)])),
                ('can_send', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130)),
                ('brand', models.CharField(blank=True, choices=[('ADDIDAS', 'ADDIDAS'), ('PUMA', 'PUMA')], max_length=130, null=True)),
                ('price', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('avail_status', models.CharField(choices=[('INSTOCK', 'INSTOCK'), ('OUTOFSTOCK', 'OUTOFSTOCK')], max_length=40)),
                ('display_info', models.TextField()),
                ('shipping_returns_policy', models.TextField()),
                ('category', models.CharField(choices=[('CASUAL_SHOES', 'CASUAL_SHOES'), ('FORMAL_SHOES', 'FORMAL_SHOES'), ('SPORT_SHOES', 'SPORT_SHOES')], max_length=40)),
                ('label', models.CharField(blank=True, choices=[('SNEAKERS', 'SNEAKERS')], max_length=20, null=True)),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
                ('Product_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileno', models.IntegerField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('created_Entry_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImgPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('path1', models.CharField(max_length=130)),
                ('path2', models.CharField(max_length=130)),
                ('path3', models.CharField(max_length=130)),
                ('path4', models.CharField(max_length=130)),
                ('thumbpath1', models.CharField(max_length=130)),
                ('thumbpath2', models.CharField(max_length=130)),
                ('thumbpath3', models.CharField(max_length=130)),
                ('thumbpath4', models.CharField(max_length=130)),
                ('related_product_path_1', models.CharField(max_length=130)),
                ('related_product_path_2', models.CharField(max_length=130)),
                ('related_product_path_3', models.CharField(max_length=130)),
                ('related_product_path_4', models.CharField(max_length=130)),
                ('related_product_path_5', models.CharField(max_length=130)),
                ('capture_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product')),
            ],
        ),
    ]
