# Generated by Django 3.0.6 on 2021-03-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartpage_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=5000, null=True)),
                ('orderid', models.BigIntegerField(blank=True, null=True)),
                ('chargevalue', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='filterinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('category_call', models.TextField(blank=True, max_length=200, null=True)),
                ('price_call', models.TextField(blank=True, max_length=200, null=True)),
                ('color_call', models.TextField(blank=True, max_length=200, null=True)),
                ('brand_call', models.TextField(blank=True, max_length=200, null=True)),
                ('size_call', models.TextField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('locality', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=300, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=500, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_mobileno', models.CharField(blank=True, max_length=50, null=True)),
                ('orderid', models.BigIntegerField(blank=True, null=True)),
                ('Product_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=130, null=True)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('gst_added_price', models.FloatField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('process_status', models.BooleanField(blank=True, default=0, null=True)),
                ('tracking_status', models.CharField(blank=True, choices=[('ordered', 'ordered'), ('packed', 'packed'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='ordered', max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='order2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('Address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('locality', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_mode', models.CharField(blank=True, max_length=300, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=500, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=500, null=True)),
                ('alt_mobileno', models.CharField(blank=True, max_length=500, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='searchinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_search_term', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='searchinfo_by_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('search_req', models.TextField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxn_entry', models.CharField(max_length=5000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('turquoise', 'turquoise'), ('gray', 'gray'), ('orange', 'orange'), ('yellow', 'yellow'), ('green', 'green'), ('purple', 'purple'), ('blue', 'blue'), ('white', 'white')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_new_attrib',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='avail_status',
            field=models.IntegerField(blank=True, choices=[(1, 'INSTOCK'), (0, 'OUTOFSTOCK')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('addidas', 'addidas'), ('puma', 'puma'), ('nike', 'nike'), ('sketchers', 'sketchers')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('casualshoes', 'casualshoes'), ('formalshoes', 'formalshoes'), ('sneakers', 'sneakers'), ('studds', 'studds')], max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shipping_returns_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
